spring.application.name=webpilot

# SERVER
server.port=8084

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/webpilot
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# HIKARI POOL
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6382
spring.data.redis.timeout=3000

# FILE UPLOAD
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# JWT
jwt.secret=7QmP9vX2Lk8RtN5ZcY4HsW1AaE6BgFpJ3DxUqMnK8VsTzR5HyL9NcW4AeFpJ8Lk2Mx

jwt.expiration=86400000
jwt.refresh-expiration=604800000

# GEMINI
gemini.api.key=AQ.Ab8RN6JcQSTAhYVqSwtAupguv2VLC3VMCv2oj2bkegooKMN7Gw
gemini.model=gemini-3.5-flash
gemini.url=https://generativelanguage.googleapis.com/v1beta

# LOGGING
logging.level.root=INFO
logging.level.com.webpilot=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# JACKSON
spring.jackson.serialization.indent-output=true

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# COMPRESSION
server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/plain
server.compression.min-response-size=1024